var colors = {
    customClass: {
        titleBackground: "#DAEEFD",
        titleBorder: "#DAEEFD",
        propBackground: "#FFFFFF",
        propBorder: "#DAEEFD",
    },
    androidComponent: {
        titleBackground: "#8BC34A",
        titleBorder: "#8BC34A",
        propBackground: "#FFFFFF",
        propBorder: "#8BC34A",
        textColor: "#FFFFFF"
    }

}

var widgets = [
// Direct Subclasses of View
"AnalogClock",
"ImageView",
"KeyboardView",
"MediaRouteButton",
"ProgressBar",
"Space",
"SurfaceView",
"TextView",
"TextureView",
"ViewStub",
];
// Indirect Subclasses of View
// "AbsListView",
// "AbsSeekBar",
// "AbsSpinner",
// "ActionMenuView",
// "AppCompatAutoCompleteTextView",
// "AppCompatButton",
// "AppCompatCheckBox",
// "AppCompatCheckedTextView",
// "AppCompatEditText",
// "AppCompatImageButton",
// "AppCompatImageView",
// "AppCompatMultiAutoCompleteTextView",
// "AppCompatRadioButton",
// "AppCompatRatingBar",
// "AppCompatSeekBar",
// "AppCompatSpinner",
// "AppCompatTextView",
// "AppWidgetHostView",
// "AutoCompleteTextView",
// "Button",
// "CalendarView",
// "CheckBox",
// "CheckedTextView",
// "Chronometer",
// "CompoundButton",
// "ContentLoadingProgressBar",
// "DatePicker",
// "DialerFilter",
// "DigitalClock",
// "EditText",
// "ExpandableListView",
// "ExtractEditText",
// "FloatingActionButton",
// "FragmentBreadCrumbs",
// "FragmentTabHost",
// "GLSurfaceView",
// "GestureOverlayView",
// "GuidedActionEditText",
// "ImageButton",
// "ImageCardView",
// "ImageSwitcher",
// "ListRowHoverCardView",
// "ListView",
// "MediaController",
// "MultiAutoCompleteTextView",
// "NavigationView",
// "NumberPicker",
// "PagerTabStrip",
// "PagerTitleStrip",
// "QuickContactBadge",
// "RadioButton",
// "RadioGroup",
// "RatingBar",
// "RecyclerView",
// "RowHeaderView",
// "SearchBar",
// "SearchEditText",
// "SearchOrbView",
// "SearchView",
// "SeekBar",
// "SlidingDrawer",
// "SlidingPaneLayout",
// "Space",
// "SpeechOrbView",
// "Spinner",
// "StackView",
// "Switch",
// "SwitchCompat",
// "TabWidget",
// "TextClock",
// "TextSwitcher",
// "TimePicker",
// "TitleView",
// "ToggleButton",
// "Toolbar",
// "TvView",
// "VideoView",
// "WebView",
// "ZoomButton",
// "ZoomControls",

var layouts = [
// Direct Subclasses of ViewGroup
"AbsoluteLayout",
"AdapterView",
"CoordinatorLayout",
"DrawerLayout",
"FragmentBreadCrumbs",
"FrameLayout",
"GridLayout",
"LinearLayout",
"LinearLayoutCompat",
"PagerTitleStrip",
"RecyclerView",
"RelativeLayout",
"SlidingDrawer",
"SlidingPaneLayout",
"SwipeRefreshLayout",
"Toolbar",
"TvView",
"ViewGroup",
"ViewPager",
];
// Indirect Subclasses of ViewGroup
// "AbsListView",
// "AbsSpinner",
// "ActionMenuView",
// "AdapterViewAnimator",
// "AdapterViewFlipper",
// "AppBarLayout",
// "AppCompatSpinner",
// "AppWidgetHostView",
// "BaseCardView",
// "BrowseFrameLayout",
// "CalendarView",
// "CardView",
// "CollapsingToolbarLayout",
// "DatePicker",
// "DialerFilter",
// "ExpandableListView",
// "FragmentTabHost",
// "Gallery",
// "GestureOverlayView",
// "GridView",
// "HorizontalGridView",
// "HorizontalScrollView",
// "ImageCardView",
// "ImageSwitcher",
// "ListRowHoverCardView",
// "ListRowView",
// "ListView",
// "MediaController",
// "NavigationView",
// "NestedScrollView",
// "NumberPicker",
// "PagerTabStrip",
// "PercentFrameLayout",
// "PercentRelativeLayout",
// "RadioGroup",
// "ScrollView",
// "SearchBar",
// "SearchOrbView",
// "SearchView",
// "ShadowOverlayContainer",
// "SpeechOrbView",
// "Spinner",
// "StackView",
// "TabHost",
// "TabLayout",
// "TabWidget",
// "TableLayout",
// "TableRow",
// "TextInputLayout",
// "TextSwitcher",
// "TimePicker",
// "TitleView",
// "TwoLineListItem",
// "VerticalGridView",
// "ViewAnimator",
// "ViewFlipper",
// "ViewSwitcher",
// "WebView",
// "ZoomControls",

var ClassTypes = {
    abstract: {
        id: "abstract",
        name: "Abstract",
        icon: ""
    },
    class: {
        id: "custom",
        name: "Class",
        icon: ""
    },
    interface: {
        id: "interface",
        name: "Interface",
        icon: ""
    },
}

var AndroidComponents = {
    activity: {
        id: "activity",
        name: "Activity",
        icon: 'img/activity.png',
    },
    broadcastReceiver: {
        id: 'broadcastReceiver',
        name: "Broadcast Receiver",
        icon: 'img/broadcast-receiver.png',
    },
    contentProvider: {
        id: 'contentProvider',
        name: "Content Provider",
        icon: 'img/content-provider.png',
    },
    explicitIntent:{
        id: 'explicitIntent',
        name: "Explicit Intent",
        icon: 'img/intent.png',
    },
    implicitIntent:{
        id: 'implicitIntent',
        name: "Implicit Intent",
        icon: 'img/implicit-intent.png',
    },
    layout: {
        id: 'layout',
        name: "Layout",
        icon: 'img/layout.png',
    },
    service: {
        id: 'service',
        name: "Service",
        icon: 'img/cog.png',
    },
    widget: {
        id: 'widget',
        name: "Widget",
        icon: 'img/widget.png'
    },
    noicon:{
      id: 'noicon',
      name: "No Icon",
      icon: ''
    }

}

var UmlLinks = {
    aggregation: {
        id: 'aggregation',
        name: "Aggregation",
        icon: "img/aggregation.png",
    },
    association: {
        id: 'association',
        name: "Association",
        icon: "img/association.png",
    },
    composition: {
        id: 'composition',
        name: "Composition",
        icon: "img/composition.png",
    },
    generalization: {
        id: 'generalization',
        name: "Generalization",
        icon: "img/generalization.png",
    },
    implementation: {
        id: 'implementation',
        name: "Implementation",
        icon: "img/implementation.png",
    },

}
